"""EDA 叙述报告生成器。

读取一次 EDA 运行产出的结构化结果（eda_summary.json / eda_recommendations.json /
data_quality.json 与可选的聚合审计 JSON），渲染成一份中文 EDA_REPORT.md。

设计原则：
- 纯函数，只读已有 JSON / plots 目录，绝不重算诊断。
- 复用 eda_recommendations.json 已算好的建议（阈值已在 recommendations.py 应用），
  本模块只负责"叙述解释"（平稳性方向、ARCH/White/BP 折中、FFT≈N 伪周期、谐波、
  BDS 警示、forecastability 语义等）。
- 输入缺失时优雅降级（省略对应内容而非报错）；eda_summary.json 缺失则放弃生成。
- 与 config / data_provider 解耦：cfg 与 aggregation_result 仅作字符串注解的鸭子类型，
  通过 getattr 防御式读取，不在运行期 import 它们。
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import TYPE_CHECKING, Any

from utils.log_util import logger

if TYPE_CHECKING:
    from config.default import AppConfig
    from data_provider.data_aggregate import AggregationResult


AUTOGEN_MARKER = (
    "<!-- auto-generated by eda/report_generator.py; "
    "set eda_report_overwrite=true to regenerate -->"
)

_METHOD_ZH = {
    "max": "最大值",
    "mean": "均值",
    "sum": "合计",
    "min": "最小值",
    "median": "中位数",
}


# ##############################
# 基础工具：读取 / 格式化 / 取值
# ##############################
def _read_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _is_num(x: Any) -> bool:
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        return False
    try:
        return not (math.isnan(x) or math.isinf(x))
    except (TypeError, ValueError):
        return False


def _as_float(x: Any) -> float | None:
    return float(x) if _is_num(x) else None


def _sget(obj: dict | None, *keys: str, default: Any = None) -> Any:
    cur: Any = obj
    for k in keys:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(k)
        if cur is None:
            return default
    return cur


def _fmt_num(x: Any, d: int = 2) -> str:
    v = _as_float(x)
    return f"{v:,.{d}f}" if v is not None else "—"


def _fmt_int(x: Any) -> str:
    try:
        return f"{int(x):,}"
    except (TypeError, ValueError):
        return "—"


def _fmt_pvalue(p: Any) -> str:
    v = _as_float(p)
    if v is None:
        return "—"
    if v <= 0:
        return "接近 0"
    if v < 1e-3:
        return f"{v:.2e}"
    return f"{v:.3f}"


def _fmt_pct(x: Any, d: int = 1) -> str:
    v = _as_float(x)
    return f"{v * 100:.{d}f}%" if v is not None else "—"


def _freq_zh(freq: Any) -> str:
    """把频率 token 翻成中文单位词，如 D→日、5min→5 分钟、1h→1 小时。"""
    if not freq:
        return ""
    s = str(freq).strip()
    low = s.lower()
    num = ""
    while low[:1].isdigit():
        num += low[0]
        low = low[1:]
    base = {
        "d": "日",
        "w": "周",
        "m": "月",
        "q": "季",
        "y": "年",
        "a": "年",
        "h": "小时",
        "min": "分钟",
        "t": "分钟",
        "s": "秒",
    }.get(low, low)
    return f"{num}{base}" if base else s


def _has_plot(output_dir: Path, name: str) -> bool:
    return (output_dir / "plots" / f"{name}.png").exists()


def _plot_ref(output_dir: Path, name: str, alt: str) -> str:
    return f"![{alt}](plots/{name}.png)" if _has_plot(output_dir, name) else ""


def _confidence_zh(conf: Any) -> str:
    c = str(conf).lower() if conf is not None else ""
    return {"high": "置信度高", "medium": "置信度中", "low": "置信度低"}.get(c, "")


def _stationarity_by_name(summary: dict | None) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for row in _sget(summary, "stationarity", default=[]) or []:
        if isinstance(row, dict) and row.get("name"):
            out[str(row["name"])] = row
    return out


# ##############################
# 叙述解释规则（这些不在任何 JSON，是本模块的价值所在）
# ##############################
def _stationarity_direction(name: str, row: dict | None) -> str:
    """ADF/PP 原假设=单位根；KPSS 原假设=平稳（方向相反）。"""
    if not row:
        return "检验缺失，无法判断"
    if row.get("ok") is False:
        return f"检验失败（{row.get('error') or '异常'}），无法判断"
    p = _as_float(row.get("pvalue"))
    if p is None:
        return "检验失败或样本不足，无法判断"
    if name == "kpss":
        return (
            "拒绝平稳原假设，支持非平稳判断"
            if p < 0.05
            else "不能拒绝平稳原假设"
        )
    # adf / pp
    return (
        "不能拒绝单位根，支持非平稳判断"
        if p > 0.05
        else "拒绝单位根，支持平稳判断"
    )


def _arch_vs_white(arch_p: Any, white_p: Any, bp_p: Any) -> str:
    a = _as_float(arch_p)
    if a is None:
        return "ARCH-LM 检验失败或样本不足（需差分后样本数 ≥ 20）"
    if a >= 0.05:
        return "未检测到显著的条件异方差"
    w = _as_float(white_p)
    b = _as_float(bp_p)
    fixed = (w is not None and w < 0.05) or (b is not None and b < 0.05)
    if fixed:
        return "存在异方差，其中部分可由时间趋势解释"
    return "更接近随时间聚集的波动（条件异方差），而非由某个简单解释变量驱动的固定形式异方差"


def _is_fft_artifact(fft_period: Any, n_samples: Any) -> bool:
    fp = _as_float(fft_period)
    n = _as_float(n_samples)
    if fp is None or n is None or n <= 0:
        return False
    return abs(fp - n) <= 1 or fp / n > 0.9


def _harmonic_note(acf_peak: Any, configured_period: Any) -> str:
    peak = _as_float(acf_peak)
    period = _as_float(configured_period)
    if peak is None or period is None or period <= 0:
        return ""
    k = peak / period
    if abs(k - round(k)) < 1e-6 and round(k) > 1:
        return f"该滞后恰为 {int(round(k))} 个整周期，更可能是周季节性的倍频/谐波，而非独立周期"
    return ""


def _ljung_box_note(lb_p: Any) -> str:
    p = _as_float(lb_p)
    if p is None:
        return "Ljung-Box 检验缺失。"
    if p < 0.05:
        return "明确拒绝白噪声假设，序列包含可利用的时间依赖结构，模型残差也必须重新检查自相关。"
    return "未拒绝白噪声假设，序列的时间依赖结构较弱。"


def _bds_note(p2: Any, p3: Any) -> str:
    a = _as_float(p2)
    b = _as_float(p3)
    if a is None and b is None:
        return "BDS 检验缺失。"
    if (a is not None and a < 0.05) or (b is not None and b < 0.05):
        return (
            "BDS 检验显著，序列不符合独立同分布假设，可能包含线性自相关之外的结构；"
            "但 BDS 本身不能证明具体的非线性机制，应在去趋势、差分并拟合均值模型后对残差再次检验。"
        )
    return "BDS 检验未拒绝独立同分布假设。"


def _forecastability_note(score: Any) -> str:
    v = _as_float(score)
    if v is None:
        return ""
    level = (
        "结构较简单、可预测性偏高"
        if v >= 0.4
        else "可预测性中等"
        if v >= 0.2
        else "可预测性偏低、噪声/随机成分较多"
    )
    return (
        f"forecastability={_fmt_num(score, 3)}（基于谱熵的相对评分，{level}）；"
        "该分数仅作模型复杂度的辅助信号，不可解释为可达预测准确率。"
    )


def _outlier_note(rate_iqr: Any, rate_z: Any) -> str:
    r = max(_as_float(rate_iqr) or 0.0, _as_float(rate_z) or 0.0)
    if r >= 0.03:
        return "异常率较高，建议结合业务事件与原始高频曲线核对后，再考虑针对性去噪。"
    return "异常率低，不建议默认启用全局去噪；应先定位异常日期、结合原始曲线确认其真实性。"


# ##############################
# 输入加载与覆盖决策
# ##############################
def _load_inputs(
    output_dir: Path,
    cfg: "AppConfig | None",
    aggregation_result: "AggregationResult | None",
    data_name: str | None,
) -> dict[str, Any]:
    summary = _read_json(output_dir / "eda_summary.json")
    recommendations = _read_json(output_dir / "eda_recommendations.json")
    data_quality = _read_json(output_dir / "data_quality.json")

    audit: dict | None = None
    if aggregation_result is not None:
        audit_path = getattr(aggregation_result, "audit_path", None)
        if audit_path:
            audit = _read_json(Path(audit_path))

    def cfg_get(name: str, default=None):
        return getattr(cfg, name, default) if cfg is not None else default

    agg_enabled = bool(cfg_get("aggregation_enabled", False)) or audit is not None
    method = _sget(audit, "config", "method") or cfg_get("aggregation_method")
    aggregation = None
    if audit is not None or agg_enabled:
        aggregation = {
            "source_freq": _sget(audit, "config", "source_freq") or cfg_get("aggregation_source_freq"),
            "method": method,
            "method_zh": _METHOD_ZH.get(str(method).lower(), str(method) if method else ""),
            "fill_method": _sget(audit, "config", "fill_method") or cfg_get("aggregation_fill_method"),
            "fill_weeks": _sget(audit, "config", "fill_weeks") or cfg_get("aggregation_fill_weeks"),
            "source_rows": _sget(audit, "source_rows"),
            "output_rows": _sget(audit, "output_rows"),
            "inserted": _sget(audit, "inserted_timestamp_count"),
            "filled": _sget(audit, "filled_value_count"),
            "dup": _sget(audit, "duplicate_timestamp_count"),
            "time_range_start": _sget(audit, "time_range_start"),
            "time_range_end": _sget(audit, "time_range_end"),
        }

    n_samples = _sget(summary, "n_samples") or _sget(data_quality, "clean_rows") or _sget(audit, "output_rows")
    name = data_name or _sget(data_quality, "target_col") or "时间序列"
    return {
        "data_name": name,
        "freq": cfg_get("freq"),
        "time_col": cfg_get("time_col"),
        "target_col": cfg_get("target_col"),
        "summary": summary,
        "recommendations": recommendations,
        "data_quality": data_quality,
        "aggregation": aggregation,
        "n_samples": n_samples,
    }


def _decide_overwrite(report_path: Path, force: bool) -> str:
    if force or not report_path.exists():
        return "write"
    try:
        head = report_path.read_text(encoding="utf-8")[:400]
    except OSError:
        return "write"
    return "skip" if AUTOGEN_MARKER not in head else "write"


# ##############################
# 各段 builder
# ##############################
def build_title(ctx: dict) -> list[str]:
    name = ctx.get("data_name") or "时间序列"
    return [f"# {name} EDA 报告", ""]


def _exec_summary(ctx: dict) -> list[str]:
    s = ctx.get("summary") or {}
    rec = ctx.get("recommendations") or {}
    bullets: list[str] = []
    ts = _as_float(_sget(s, "decomposition", "trend_strength"))
    ss = _as_float(_sget(s, "decomposition", "seasonal_strength"))
    period = _sget(s, "decomposition", "period")
    if ts is not None:
        dominate = "由显著上升趋势主导" if ts >= 0.6 else "趋势成分明显" if ts >= 0.35 else "趋势成分较弱"
        head = f"- 序列{dominate}，趋势强度 **{_fmt_num(ts, 3)}**；"
        if ss is not None and period is not None:
            head += f"以配置周期 {int(period)} 的季节强度仅为 **{_fmt_num(ss, 3)}**，季节性较弱。"
        bullets.append(head)

    d = _sget(rec, "differencing", "recommended_d")
    big_d = _sget(rec, "differencing", "recommended_D")
    stat = _stationarity_by_name(s)
    if stat:
        bullets.append(
            "- 平稳性检验（ADF/PP/KPSS）一致指向"
            + ("非平稳" if d else "近似平稳")
            + f"，建议普通差分 `d={d}`、季节差分 `D={big_d}`。"
        )

    lb_p = _sget(s, "white_noise", "ljung_box_pvalue")
    if _as_float(lb_p) is not None:
        bullets.append(
            "- " + ("原序列存在很强的序列相关性，不是白噪声，历史信息具有预测价值；模型必须处理趋势与自相关。"
                    if _as_float(lb_p) < 0.05 else "序列接近白噪声，时间依赖结构较弱。")
        )

    arch_p = _sget(s, "heteroskedasticity", "arch_lm_pvalue")
    if _as_float(arch_p) is not None:
        bullets.append(
            "- ARCH-LM 检验" + ("显著，残差波动可能具有条件异方差（波动聚集）。" if _as_float(arch_p) < 0.05 else "不显著，未提示明显条件异方差。")
        )

    rec_period = _sget(rec, "seasonal_period", "recommended_period")
    fft = _sget(s, "cycle", "dominant_period_fft")
    if rec_period is not None or _is_fft_artifact(fft, ctx.get("n_samples")):
        part = f"自动周期建议给出 {int(rec_period)} 天候选（置信度低）。" if rec_period is not None else ""
        fft_part = "FFT 主周期接近样本长度，主要反映趋势或有限样本边界，不应直接解释为业务周期。" if _is_fft_artifact(fft, ctx.get("n_samples")) else ""
        bullets.append("- " + " ".join(p for p in (part, fft_part) if p))

    n_iqr = _sget(s, "outliers", "n_outliers_iqr")
    if n_iqr is not None:
        bullets.append(f"- 仅检测到 **{_fmt_int(n_iqr)}** 个异常点（异常率约 **{_fmt_pct(_sget(s, 'outliers', 'outlier_rate_iqr'), 2)}**），不支持大范围异常值替换。")

    cands = _sget(rec, "model_family", "candidates") or []
    if cands:
        bullets.append(f"- 建议优先比较的模型族：{', '.join(cands)}；模型选择以滚动回测为准。")

    return ["## 技术摘要", "", *bullets, ""]


def build_section_1(ctx: dict) -> list[str]:
    s = ctx.get("summary") or {}
    dq = ctx.get("data_quality") or {}
    agg = ctx.get("aggregation")
    target_freq = ctx.get("freq")
    rows: list[str] = []

    def add(label: str, value: Any):
        rows.append(f"| {label} | {value} |")

    if agg and agg.get("source_freq"):
        add("原始频率", _freq_zh(agg["source_freq"]) or agg["source_freq"])
    if target_freq:
        add("建模频率", (_freq_zh(target_freq) or target_freq) + "频")
    if agg and agg.get("method_zh"):
        add("日值定义", f"当日{agg['method_zh']}")
    tr_start = (agg.get("time_range_start") if agg else None) or _sget(dq, "time_range_start")
    tr_end = (agg.get("time_range_end") if agg else None) or _sget(dq, "time_range_end")
    if tr_start and tr_end:
        add("时间范围", f"{tr_start} 至 {tr_end}")
    if agg and agg.get("source_rows") is not None:
        add("原始记录数", _fmt_int(agg["source_rows"]))
    add("建模记录数", _fmt_int(ctx.get("n_samples") or _sget(dq, "clean_rows")))
    if agg and agg.get("inserted") is not None:
        add("补齐并填充的时间点", _fmt_int(agg["inserted"]))
    if agg and agg.get("dup") is not None:
        add("重复时间戳", _fmt_int(agg["dup"]))
    add("建模序列缺失率", _fmt_pct(_sget(s, "missing_rate", default=_sget(dq, "missing_ratio"))))

    lines = ["## 1. 数据口径与质量", ""]
    if rows:
        lines += ["| 项目 | 结果 |", "| --- | ---: |", *rows, ""]
    else:
        lines += ["（数据口径信息不足）", ""]

    if agg and agg.get("source_freq"):
        fill = agg.get("fill_method")
        weeks = agg.get("fill_weeks")
        fill_desc = {
            "seasonal_slot": f"`seasonal_slot`：对每个缺失时间点，使用前后 {weeks or 'N'} 周内相同星期与相同时刻的有效观测均值。",
            "linear": "`linear`：按时间线性插值。",
            "none": "`none`：不填充（缺失会直接暴露并在聚合时被严格校验拒绝）。",
        }.get(str(fill), f"`{fill}`")
        lines += [
            f"该序列由源频率 {_freq_zh(agg['source_freq']) or agg['source_freq']} 聚合而来，缺失值使用 {fill_desc}",
            "填充值并非真实测量值；涉及异常日、节假日或设备状态变化时，应回看原始高频序列与聚合审计。",
            "",
        ]
    elif agg is None:
        lines += ["本数据未启用频率聚合（直接以建模频率输入）。", ""]
    return lines


def build_section_2(ctx: dict, output_dir: Path) -> list[str]:
    s = ctx.get("summary") or {}
    rec = ctx.get("recommendations") or {}
    lines = [
        "## 2. 趋势与水平",
        "",
        f"均值为 **{_fmt_num(_sget(s, 'mean'))}**，标准差 **{_fmt_num(_sget(s, 'std'))}**，"
        f"最小值 **{_fmt_num(_sget(s, 'min'))}**，最大值 **{_fmt_num(_sget(s, 'max'))}**；"
        f"四分位区间 {_fmt_num(_sget(s, 'q1'))} 至 {_fmt_num(_sget(s, 'q3'))}。",
        f"偏度 **{_fmt_num(_sget(s, 'skewness'), 3)}**，"
        + ("整体分布近似对称；" if abs(_as_float(_sget(s, 'skewness')) or 0) < 0.5 else "分布存在偏态；")
        + f"峰度 **{_fmt_num(_sget(s, 'kurtosis'), 3)}**，"
        + ("较正态分布更平缓。" if (_as_float(_sget(s, 'kurtosis')) or 0) < 0 else "较正态分布更尖峭。"),
        "",
    ]
    ref = _plot_ref(output_dir, "series", "时序图")
    if ref:
        lines += [ref, ""]
    ts = _as_float(_sget(s, "decomposition", "trend_strength"))
    rstd = _sget(s, "decomposition", "residual_std")
    if ts is not None:
        lines.append(f"STL 分解的趋势强度为 **{_fmt_num(ts, 3)}**，绝大部分可解释变化来自长期水平变化。")
    if _as_float(rstd) is not None:
        mean_v = _as_float(_sget(s, "mean")) or 0.0
        pct = (rstd / mean_v * 100) if mean_v else None
        lines.append(
            f"同期残差标准差为 **{_fmt_num(rstd)}**"
            + (f"，约为均值的 {_fmt_pct(pct / 100)}，可作为去趋势、去季节后的噪声底盘参考。" if pct else "。")
        )
    lines.append("")
    ref = _plot_ref(output_dir, "trend", "趋势分量")
    if ref:
        lines += [ref, ""]
    detrend = _sget(rec, "preprocessing", "detrend_method")
    d = _sget(rec, "differencing", "recommended_d")
    lines.append(
        f"建模时应优先处理趋势。当前自动建议为 `detrend_method={detrend}`、差分 `d={d}`；"
        "实际实验中不应同时无条件叠加「线性去趋势」与「一阶差分」两种处理，应分别建立候选配置并通过滚动回测取舍。"
    )
    lines.append("")
    fb = _forecastability_note(_sget(s, "forecastability"))
    if fb:
        lines += [fb, ""]
    return lines


def build_section_3(ctx: dict, output_dir: Path) -> list[str]:
    s = ctx.get("summary") or {}
    rec = ctx.get("recommendations") or {}
    ss = _as_float(_sget(s, "decomposition", "seasonal_strength"))
    period = _sget(s, "decomposition", "period")
    lines = ["## 3. 季节性与周期", ""]
    if ss is not None:
        lines.append(f"以配置周期 {period} 进行 STL 分解时，季节强度为 **{_fmt_num(ss, 3)}**，" + (
            "明显低于趋势强度。" if ss < 0.35 else "存在不可忽视的季节结构。"))
    d_ch = _sget(s, "seasonal_diff", "D_ch")
    d_ocsb = _sget(s, "seasonal_diff", "D_ocsb")
    if d_ch is not None or d_ocsb is not None:
        lines.append(f"CH 与 OCSB 季节差分检验分别建议 `D={_fmt_int(d_ch)}` / `{_fmt_int(d_ocsb)}`，当前不支持直接进行季节差分。")
    lines.append("")
    ref = _plot_ref(output_dir, "seasonal", "季节分量")
    if ref:
        lines += [ref, ""]
    acf_peaks = _sget(s, "cycle", "acf_peak_lags") or []
    rec_period = _sget(rec, "seasonal_period", "recommended_period")
    conf = _sget(rec, "seasonal_period", "confidence")
    fft = _sget(s, "cycle", "dominant_period_fft")
    parts = []
    if acf_peaks:
        parts.append(f"ACF 峰值检测识别到 {', '.join(str(int(p)) for p in acf_peaks)} 天滞后")
        harm = _harmonic_note(acf_peaks[0], period)
        if harm:
            parts.append(harm)
    if rec_period is not None:
        parts.append(f"自动建议将 {int(rec_period)} 作为低置信度候选周期（{_confidence_zh(conf)}）")
    if parts:
        lines.append("；".join(parts) + "。")
    if _is_fft_artifact(fft, ctx.get("n_samples")):
        lines.append("FFT 主周期接近完整样本长度，通常是强趋势与有限观察窗口造成的低频能量集中，不能视为稳定业务周期。")
    lines.append("上述周期候选都需要在去趋势或一阶差分后的序列上重新验证，并通过样本外回测确认。")
    lines.append("")
    ref = _plot_ref(output_dir, "periodogram", "周期图")
    if ref:
        lines += [ref, ""]
    return lines


def build_section_4(ctx: dict, output_dir: Path) -> list[str]:
    s = ctx.get("summary") or {}
    rec = ctx.get("recommendations") or {}
    stat = _stationarity_by_name(s)
    lines = ["## 4. 平稳性与自相关", ""]
    rows = []
    display = [("ADF", "adf"), ("PP", "pp"), ("KPSS", "kpss")]
    for label, key in display:
        row = stat.get(key)
        if row:
            rows.append(
                f"| {label} | {_fmt_num(row.get('statistic'), 3)} | {_fmt_pvalue(row.get('pvalue'))} | "
                f"{_stationarity_direction(key, row)} |"
            )
    if rows:
        lines += ["| 检验 | 统计量 | p 值 | 解释 |", "| --- | ---: | ---: | --- |", *rows, ""]
    d = _sget(rec, "differencing", "recommended_d")
    big_d = _sget(rec, "differencing", "recommended_D")
    lines.append(f"综合三个检验方向，普通差分建议 `d={d}`、季节差分 `D={big_d}`（{_confidence_zh(_sget(rec, 'differencing', 'confidence'))}）。")
    acf1 = (_sget(s, "acf_head") or [None, None])
    pacf1 = (_sget(s, "pacf_head") or [None, None])
    acf1 = acf1[1] if len(acf1) > 1 else None
    pacf1 = pacf1[1] if len(pacf1) > 1 else None
    if _as_float(acf1) is not None or _as_float(pacf1) is not None:
        lines.append(
            f"原序列一阶自相关系数约 **{_fmt_num(acf1, 3)}**，PACF 在滞后 1 处约 **{_fmt_num(pacf1, 3)}**，"
            "随后明显下降，符合需要差分或 AR(1) 主导的结构。"
        )
    lines.append("")
    ref = _plot_ref(output_dir, "acf_pacf", "ACF 与 PACF")
    if ref:
        lines += [ref, ""]
    lb_stat = _sget(s, "white_noise", "ljung_box_stat")
    lb_p = _sget(s, "white_noise", "ljung_box_pvalue")
    lines.append(f"Ljung-Box 统计量为 {_fmt_num(lb_stat)}，p 值 {_fmt_pvalue(lb_p)}。{_ljung_box_note(lb_p)}")
    lines.append("")
    ref = _plot_ref(output_dir, "difference", "一阶差分")
    if ref:
        lines += [ref, ""]
    return lines


def build_section_5(ctx: dict, output_dir: Path) -> list[str]:
    s = ctx.get("summary") or {}
    arch_p = _sget(s, "heteroskedasticity", "arch_lm_pvalue")
    white_p = _sget(s, "heteroskedasticity", "white_pvalue")
    bp_p = _sget(s, "heteroskedasticity", "bp_pvalue")
    lines = [
        "## 5. 波动与异常",
        "",
        f"ARCH-LM 统计量为 {_fmt_num(_sget(s, 'heteroskedasticity', 'arch_lm_stat'))}，p 值 {_fmt_pvalue(arch_p)}；"
        f"White p={_fmt_pvalue(white_p)}、Breusch-Pagan p={_fmt_pvalue(bp_p)}。"
        + _arch_vs_white(arch_p, white_p, bp_p) + "。",
        "",
    ]
    p2 = _sget(s, "stochasticity", "bds_pvalue_dim2")
    p3 = _sget(s, "stochasticity", "bds_pvalue_dim3")
    lines.append(_bds_note(p2, p3))
    lines.append("")
    ref = _plot_ref(output_dir, "residual", "残差分量")
    if ref:
        lines += [ref, ""]
    n_iqr = _sget(s, "outliers", "n_outliers_iqr")
    n_z = _sget(s, "outliers", "n_outliers_zscore")
    rate_iqr = _sget(s, "outliers", "outlier_rate_iqr")
    rate_z = _sget(s, "outliers", "outlier_rate_zscore")
    lines.append(
        f"IQR 与 Z-score 方法分别识别到 {_fmt_int(n_iqr)} / {_fmt_int(n_z)} 个异常点"
        f"（异常率约 {_fmt_pct(rate_iqr, 2)} / {_fmt_pct(rate_z, 2)}）。{_outlier_note(rate_iqr, rate_z)}"
    )
    lines.append("")
    ref = _plot_ref(output_dir, "distribution", "分布")
    if ref:
        lines += [ref, ""]
    return lines


def build_section_6(ctx: dict) -> list[str]:
    rec = ctx.get("recommendations") or {}
    lines = ["## 6. 建模建议", ""]
    if not rec:
        lines += ["未生成建模建议（`eda_recommendation_enabled=false`）；请依据 §2–§5 自行决策。", ""]
        return lines
    cands = _sget(rec, "model_family", "candidates") or []
    d = _sget(rec, "differencing", "recommended_d")
    big_d = _sget(rec, "differencing", "recommended_D")
    detrend = _sget(rec, "preprocessing", "detrend_method")
    decomp = _sget(rec, "preprocessing", "decomposition_method")
    denoise = _sget(rec, "preprocessing", "denoise_method")
    rec_period = _sget(rec, "seasonal_period", "recommended_period")
    steps = []
    if cands:
        steps.append(f"**基线与主候选**：优先比较 {', '.join(cands)}。")
    steps.append(f"**差分**：`d={d}`、`D={big_d}`；AR/MA 阶数参考差分后 ACF/PACF，由滚动回测选择。")
    steps.append(f"**预处理**：`detrend_method={detrend}`、`decomposition_method={decomp}`、`denoise_method={denoise}`（默认保持轻量）。")
    if rec_period is not None:
        steps.append(f"**季节性**：把配置周期与 {int(rec_period)} 候选都作为实验变量，当前证据不支持直接季节差分。")
    steps.append("**波动**：若业务关心预测区间或峰值风险，可在均值模型残差仍存 ARCH 效应时叠加 ARCH/GARCH；不以 GARCH 替代负荷均值预测。")
    steps.append("**异常值**：默认 `denoise_method=none`，仅在核验异常日期后针对性处理。")
    lines += ["建议按以下顺序构建和比较模型：", ""]
    for i, st in enumerate(steps, 1):
        lines.append(f"{i}. {st}")
    lines += [
        "",
        "模型选择应以时间顺序滚动回测为准，重点比较 MAE、RMSE、MAPE 以及高负荷区间误差，"
        "并单独检查预测偏差是否随时间增长、模型在后半段高负荷水平上是否存在系统性低估。",
        "",
    ]
    return lines


def build_section_7(ctx: dict) -> list[str]:
    s = ctx.get("summary") or {}
    agg = ctx.get("aggregation")
    n = ctx.get("n_samples")
    lines = ["## 7. 限制与稳健性边界", ""]
    lines.append(f"- 样本约 {_fmt_int(n)} 个观测，覆盖时长有限，尚不足以验证年度季节性或多个完整业务周期。")
    if agg and agg.get("source_freq"):
        lines.append(
            f"- 本序列由 {_freq_zh(agg['source_freq']) or agg['source_freq']} 聚合为建模频率，"
            "聚合保留了目标统计量但丢失了高频曲线、峰值持续时间与峰谷差等信息；结论仅适用于当前建模频率。"
        )
    if agg and agg.get("inserted"):
        lines.append(f"- {_fmt_int(agg['inserted'])} 个源频率时间点来自统计填充，整段缺失或峰值附近缺失时可能影响当日统计量。")
    lines.append("- 季节性结论依赖配置周期；ACF/FFT 候选仅为待验证项，尚未经过样本外稳定性验证。")
    lines.append("- ARCH、BDS 等检验基于当前序列诊断，不能替代拟合后残差诊断，也不能单独证明因果或具体非线性机制。")
    fb = _forecastability_note(_sget(s, "forecastability"))
    if fb:
        lines.append(f"- {fb}")
    lines.append("")
    return lines


def build_section_8(ctx: dict) -> list[str]:
    rec = ctx.get("recommendations") or {}
    d = _sget(rec, "differencing", "recommended_d")
    detrend = _sget(rec, "preprocessing", "detrend_method")
    rec_period = _sget(rec, "seasonal_period", "recommended_period")
    lines = [
        "## 8. 后续验证问题",
        "",
        f"- 一阶差分（`d={d}`）与 `{detrend}` 去趋势，哪一种在滚动回测中更稳定？",
    ]
    if rec_period is not None:
        lines.append(f"- 配置周期与 {int(rec_period)} 候选周期是否能在不同回测窗口中持续降低误差？")
    lines += [
        "- 异常点对应的原始高频曲线是否为真实业务峰值？",
        "- 拟合均值模型后，残差是否仍存在显著 ARCH 效应与 BDS 非独立结构？",
        "- 是否需要补充高分位误差、峰值召回率或预测区间覆盖率等风险指标？",
        "",
    ]
    return lines


def build_footer(ctx: dict) -> list[str]:
    return [
        "---",
        "",
        "本报告由 `eda/report_generator.py` 依据同目录下的 `eda_summary.json`、"
        "`eda_diagnostics.csv`、`eda_recommendations.json` 与 `plots/` 图表，"
        "以及派生数据旁的聚合审计 JSON 自动生成；如需精修，可参考 `eda/EDA_REPORT_GUIDE.md`。",
        "",
    ]


# ##############################
# 编排器
# ##############################
def generate_eda_report(
    output_dir: str | Path,
    *,
    cfg: "AppConfig | None" = None,
    aggregation_result: "AggregationResult | None" = None,
    data_name: str | None = None,
    force: bool = False,
) -> str | None:
    """读取 output_dir 下已有 EDA JSON 产物，生成 EDA_REPORT.md，返回其绝对路径。

    纯函数（只读不重算）；输入缺失优雅降级；eda_summary.json 缺失则告警返回 None。
    覆盖策略：已存在且为手写（无 AUTOGEN_MARKER）默认跳过；自动生成的（含标记）会被刷新；
    force=True 一律覆盖。
    """
    out = Path(output_dir)
    ctx = _load_inputs(out, cfg, aggregation_result, data_name)
    if ctx.get("summary") is None:
        logger.warning("[EDA:report] eda_summary.json 缺失或不可读，跳过报告生成。")
        return None

    report_path = out / "EDA_REPORT.md"
    if _decide_overwrite(report_path, force) == "skip":
        logger.info(f"[EDA:report] {report_path} 已存在且为手写，跳过自动生成（如需覆盖请设 eda_report_overwrite=true）。")
        return str(report_path)

    blocks = [
        build_title(ctx),
        _exec_summary(ctx),
        build_section_1(ctx),
        build_section_2(ctx, out),
        build_section_3(ctx, out),
        build_section_4(ctx, out),
        build_section_5(ctx, out),
        build_section_6(ctx),
        build_section_7(ctx),
        build_section_8(ctx),
        build_footer(ctx),
    ]
    body = "\n\n".join("\n".join(b).rstrip() for b in blocks if b)
    content = f"{AUTOGEN_MARKER}\n\n{body}\n"
    report_path.write_text(content, encoding="utf-8")
    logger.info(f"[EDA:report] 生成 {report_path}")
    return str(report_path)
